[package]
name = "gem2gef"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
flate2 = "1"
anyhow = "1"
hdf5 = { package = "hdf5-metno", version = "0.10.2"}
ndarray = "0.16.0"
chrono = "0.4"